### ISSUE TITLE
Vancouver time do not update when time goes by

### ISSUE THREAD

**Issue by lddv** [cleiver/vanclock#1]
Awesome job on this tool. 👍 
I also liked how you highlighted other important cities in the world. Great feature! 🎉 

Now, to the issue. I used it for a few minutes and noticed that Vancouver time stands still, as it seems to be calculated when I opened the page.

Maybe a routine that checks the clock on the left by minute (or even less, just in case I get into the page at, say, 10:46:59) would be enough to keep that in sync.

Again, just a minor thing, and if I could help in my spare time, I could also submit a PR for this. Meanwhile, just reporting to let you know.

**Comment by cleiver** [comment]
I did it with Vancouver time, but then when I was working on world time I had some issues and decided to keep it static for now.

This world map I got from moment.js site, I'm thinking in maybe breaking the code into smaller functions. 

Unfortunately for me JavaScript is something I can read but suck at writing 😒

**Comment by lddv** [comment]
I was working on that fix, but I couldn't push my branch somehow.

```
ERROR: Permission to cleiver/vanclock.git denied to lddv.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

~Could you please give me permission to push code? You can revoke it once I get my PR up if you want.~ Nevermind, I forked your repo and created a pull request. Hope it helps.

**Comment by cleiver** [comment]
I was browsing my settings to see if there was any options blocking people to  create PR when you update here 😅

Great addition! Gonna merge the file, thanks! 🤟
